<?php

namespace Planck\Theme\Yummy\Layout;


class Main extends \Planck\View\Layout
{

    public function __construct()
    {
        parent::__construct();
    }


    public function getMainContainer()
    {
        return $this->dom->find('#main-container');
    }


    public function setTitle($title)
    {
        $this->clear('title');
        $this->registerComponent($title, 'title');
        return $this;
    }


    public function build()
    {
        $html = $this->obInclude(__DIR__.'/template.php', $this->getVariables());
        $this->setHTML($html, true);
        parent::build();
    }

    public function render()
    {
        return parent::render(); // TODO: Change the autogenerated stub
    }

}

