<?php

namespace Planck\Theme\Yummy\Component;


class ArticleMeta extends \Planck\View\Component
{


    public function __construct($template = null)
    {
        parent::__construct();
        $this->template = __DIR__.'/template.php';

    }


    public function build()
    {
        parent::build(); // TODO: Change the autogenerated stub

        if($this->variableExists('article')) {


            $url = $this->getApplication()->buildRoute('author', array($this->article->getAuthor()));

                        $this->dom->find('.post-author')->html(
                            '<a href="'.$url.'">Par '.$this->article->getAuthor()->getName().'</a>'
                        );




                        $url = $this->getApplication()->buildRoute('date', array($this->article->getValue('creation_date')));
                        $this->dom->find('.post-date')->html(
                            '<a href="'.$url.'">'.\Planck\Helper\Date::formatDatetime($this->article->getValue('creation_date')).'</a>'
                        );


                        if($this->article->hasCategory()) {
                            $category = $this->article->getCategory();
                            $url = $this->getApplication()->buildRoute('category', array($category));
                            $this->dom->find('.post-category')->html(
                                '<a href="'.$url.'">'.$category->getValue('name').'</a>'
                            );
                        }

        }


    }


}