<?php


namespace Planck\Theme\Yummy\View;

use Planck\View\Component;

class Article extends Component
{


    public function render()
    {
        $this->dom->html($this->obInclude(__DIR__.'/template.php', $this->getVariables()));
        return parent::render(); // TODO: Change the autogenerated stub
    }


}