<?php

namespace Planck\Theme\Yummy\Component;


class PostThumbnail extends \Planck\View\Component
{


    public function __construct($template = null)
    {
        parent::__construct();

        if($template == null) {
            $this->template = __DIR__.'/template-default.php';
        }
        else {
            $this->template = __DIR__.'/'.$template;
        }
    }


    public function build()
    {
        parent::build(); // TODO: Change the autogenerated stub

        if($this->variableExists('article')) {


            $this->dom->find('.post-headline')->html(
                $this->getVariable('article')->getValue('title')
            );

            $this->dom->find('.article-url')->setAttribute(
                'href',
                $this->article->getValue('url')
            );


            $meta = new ArticleMeta();
            $meta->setVariable('article', $this->article);
            $this->dom->find('.post-meta')->html(
                $meta
            );




            if($this->article->hasImage()) {
                $imageURL = $this->article->getImage()->getValue('url');
                $this->dom->find('.post-thumb')->html(
                    '<a href="'.$this->article->getValue('url').'" style="background-image:url('.$imageURL.')"><img src="'.$imageURL.'"/></a>'
                );

            }
        }


    }


}